release:

before:
  hooks:
    - go mod tidy

builds:
- id: ssm
  main: ./main.go
  binary: bin/ssm
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X 'github.com/disneystreaming/ssm-helpers/cmd.version={{.Version}}' -X 'github.com/disneystreaming/ssm-helpers/cmd.commit={{.Commit}}'

archives:
- builds:
  - ssm
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

brews:
- github:
    owner: disneystreaming
    name: homebrew-ssm-helpers
  homepage: "https://github.com/disneystreaming/ssm-helpers"
  description: "Help manage systems with AWS Systems Manager with management helpers."
  folder: Formula
  dependencies:
    - awscli
    - disneystreaming/tap/aws-session-manager-plugin

dockers:
  - binaries:
    - ssm
    goos: linux
    dockerfile: Dockerfile
    image_templates:
    - "docker.pkg.github.com/disneystreaming/ssm-helpers/ssm:latest"
    - "docker.pkg.github.com/disneystreaming/ssm-helpers/ssm:{{ .Tag }}"
    - "docker.pkg.github.com/disneystreaming/ssm-helpers/ssm:{{ .Major }}"
    - "docker.pkg.github.com/disneystreaming/ssm-helpers/ssm:{{ .Major }}.{{ .Minor }}"

nfpms:
  - license: MIT
    maintainer: Disney Streaming Services
    description: Helper tools for AWS Systems Manager.
    homepage: https://github.com/disneystreaming/ssm-helpers
    suggests:
      - awscli
      - session-manager-plugin
    formats:
      - rpm
      - deb

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
