name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.x
      - name: Docker login (github packages)
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: disneystreaming
          password: ${{ secrets.GO_RELEASER }}
      - name: Docker login (ghcr)
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io 
          username: disneystreaming
          password: ${{ secrets.GO_RELEASER }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER }}
